#!/usr/bin/env python3
"""Generate a Markdown snapshot of the local inventory.yaml."""

from __future__ import annotations

import argparse
import sys
from collections import Counter
from pathlib import Path

import yaml


def repo_root() -> Path:
    """Resolve the repository root as the parent of the scripts directory."""
    return Path(__file__).resolve().parent.parent


def load_inventory(path: Path) -> list[dict]:
    try:
        data = yaml.safe_load(path.read_text(encoding="utf-8"))
    except FileNotFoundError:
        print(f"[error] inventory not found at {path}", file=sys.stderr)
        sys.exit(1)
    except OSError as exc:
        print(f"[error] Could not read {path}: {exc}", file=sys.stderr)
        sys.exit(1)
    except yaml.YAMLError as exc:
        print(f"[error] Failed to parse {path}: {exc}", file=sys.stderr)
        sys.exit(1)

    if not isinstance(data, list):
        print(
            "[error] inventory.yaml must contain a top-level list of items.",
            file=sys.stderr,
        )
        sys.exit(1)

    return data


def normalize_item(raw: object) -> dict[str, str]:
    """Convert a raw YAML item into a normalized mapping of strings."""
    if not isinstance(raw, dict):
        raw = {}

    def as_text(value: object, default: str) -> str:
        if value is None:
            return default
        return str(value)

    return {
        "id": as_text(raw.get("id", "unknown"), "unknown"),
        "kind": as_text(raw.get("kind", "unknown"), "unknown"),
        "status": as_text(raw.get("status", "unknown"), "unknown"),
        "source": as_text(raw.get("source", "unknown"), "unknown"),
        "summary": as_text(raw.get("summary", ""), ""),
    }


def compute_stats(items: list[dict[str, str]]) -> dict:
    kinds = Counter(item["kind"] for item in items)
    statuses = Counter(item["status"] for item in items)
    return {
        "total": len(items),
        "kinds": kinds,
        "statuses": statuses,
    }


def escape_cell(text: str) -> str:
    return text.replace("|", r"\|").replace("\n", " ")


def truncate_summary(text: str, limit: int = 120) -> str:
    if len(text) <= limit:
        return text
    return text[:limit] + "…"


def render_table(headers: list[str], rows: list[list[str]]) -> list[str]:
    lines = ["| " + " | ".join(headers) + " |"]
    lines.append("| " + " | ".join("---" for _ in headers) + " |")
    for row in rows:
        lines.append("| " + " | ".join(row) + " |")
    return lines


def render_report(items: list[dict[str, str]], stats: dict) -> str:
    lines: list[str] = []
    lines.append("# GPT-5.1 Memory Status (Local Inventory Snapshot)")
    lines.append("")
    lines.append(
        "This report is autogenerated from the local inventory.yaml and only reflects "
        "items tracked in this repository."
    )
    lines.append("")

    lines.append("## Summary")
    lines.append(f"- Total items: {stats['total']}")
    lines.append(f"- Distinct kinds: {len(stats['kinds'])}")
    lines.append(f"- Distinct statuses: {len(stats['statuses'])}")
    lines.append("")

    lines.append("### Counts by kind")
    kind_rows = [[escape_cell(kind), str(count)] for kind, count in sorted(stats["kinds"].items())]
    lines.extend(render_table(["Kind", "Count"], kind_rows))
    lines.append("")

    lines.append("### Counts by status")
    status_rows = [
        [escape_cell(status), str(count)] for status, count in sorted(stats["statuses"].items())
    ]
    lines.extend(render_table(["Status", "Count"], status_rows))
    lines.append("")

    lines.append("## Items")
    item_rows = []
    for item in items:
        summary = truncate_summary(item["summary"])
        item_rows.append(
            [
                escape_cell(item["id"]),
                escape_cell(item["kind"]),
                escape_cell(item["status"]),
                escape_cell(item["source"]),
                escape_cell(summary),
            ]
        )
    lines.extend(render_table(["ID", "Kind", "Status", "Source", "Summary"], item_rows))
    lines.append("")

    return "\n".join(lines)


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    default_output = Path("metadata") / "village_status.md"
    parser = argparse.ArgumentParser(description="Generate a status snapshot from inventory.yaml.")
    parser.add_argument(
        "--output",
        type=Path,
        default=default_output,
        help="Output Markdown path (default: metadata/village_status.md relative to repo root)",
    )
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    repo = repo_root()
    inventory_path = repo / "inventory.yaml"

    output_path = args.output
    if not output_path.is_absolute():
        output_path = repo / output_path

    items = [normalize_item(item) for item in load_inventory(inventory_path)]
    stats = compute_stats(items)
    report = render_report(items, stats)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    try:
        output_path.write_text(report, encoding="utf-8")
    except OSError as exc:
        print(f"[error] Could not write {output_path}: {exc}", file=sys.stderr)
        return 1

    print(f"[ok] Wrote report to {output_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
